"""Run He et al.'s OWN byte-level Anchored Decoding (AnchoredByte) on the headline's 500 prompts.

The implementation is the authors' package, `anchoreddecode` (github.com/jacqueline-he/anchored-decoding,
cloned into ext/anchored-decoding and installed editable), class BytewiseAnchoredDecodingFactory,
called exactly as their test_byte.py calls it. Nothing about the fusion, the KL solve, the byte budget
k_t = (t+1)k - prefix_debt - spent, or the prefix debt (n=5, scaled x4) is re-implemented here: this
script only chooses the prompts, the serving config, and writes the trajectories in the harness's
JSONL layout so analysis/utility.py:load_arm can read them.

Serving config = the committed Table 1 arms: temperature 1.0, no repetition penalty, no chat template,
prompt = dap.shared.load_prompt_corpus's prompt_text (the `Complete the prefix:\\n` header included),
max_new_tokens=200, which the authors' factory converts to B_max = 200 * TOKEN_TO_BYTE = 800 bytes
(their paper: T_max = 200, B_max = 800). K = k * 800 nats is the certificate.

Per trajectory it records the realised spend (their own cum_kl_spent, from log_kl_stats), the prefix
debt, the bytes generated, and the share of generated byte-steps at which the constraint binds
(fused != risky, i.e. w_risky < 1) or forces the anchor (w_risky == 0).

Usage (host B):
  CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=0 HF_HUB_OFFLINE=1 HF_HUB_CACHE=$PWD/hf_cache \\
    .venv/bin/python analysis/anchoredbyte_decode.py --risky meta-llama/Llama-3.1-8B-Instruct \\
      --k 0.5 --out-dir output/anchoredbyte/comma7b_llama8b
"""
import argparse
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from analysis.utility import CLASSES  # noqa: E402
from dap.shared import load_prompt_corpus  # noqa: E402

B_PER_T = 4          # anchoreddecode.generate_byte.TOKEN_TO_BYTE; asserted at import below


def headline_pids(opp_dir):
    """The 500 prompt ids of the committed opponent (output/sweep_plain k=-1), by class."""
    out = {}
    for c in CLASSES:
        for line in open(os.path.join(opp_dir, f"trajectories_k-1_{c}.jsonl")):
            m = json.loads(line)["metadata"]
            out[m["prompt_id"]] = c
    return out


def step_stats(hist, i, n_bytes):
    """Binding share, forced share and final spend of batch row i, over its generated byte-steps.

    `hist` is the sampler's kl_stats_history: one dict per decode step with a list per batch row.
    Row i generated `n_bytes` bytes, so steps 0..n_bytes-1 are real; later steps are the batch
    continuing for other rows (spend there is multiplied by 0 in the authors' loop)."""
    steps = hist[:n_bytes]
    bind = sum(1 for h in steps if h["bd"][i] < 1 - 1e-6)
    forced = sum(1 for h in steps if h["bd"][i] <= 1e-6)
    spend = hist[min(n_bytes, len(hist)) - 1]["cum_kl_spent"][i] if hist and n_bytes else 0.0
    return bind, forced, spend


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--safe", default="common-pile/comma-v0.1-2t")
    ap.add_argument("--risky", default="meta-llama/Llama-3.1-8B-Instruct")
    ap.add_argument("--risky-tokenizer", default="",
                    help="tokenizer id if --risky's cache entry has none (caution (aw): hash-checked)")
    ap.add_argument("--k", type=float, required=True, help="per-BYTE budget (authors' k_radius)")
    ap.add_argument("--max-new-tokens", type=int, default=200)
    ap.add_argument("--batch-size", type=int, default=16)
    ap.add_argument("--seed", type=int, default=52)
    ap.add_argument("--limit", type=int, default=0, help="smoke: first N prompts per class")
    ap.add_argument("--shard", default="0/1", help="i/n: this process decodes prompts i, i+n, ...")
    ap.add_argument("--opp-dir", default="output/sweep_plain")
    ap.add_argument("--data-dir", default="data")
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--temperature", type=float, default=1.0,
                    help="feat-205: passed to the authors' generate(), which applies it to both "
                         "log-probability vectors before the fusion; 1.0 in every run on record")
    ap.add_argument("--repetition-penalty", type=float, default=1.0, help="feat-205: likewise")
    a = ap.parse_args()

    import torch
    from transformers import AutoConfig, AutoModelForCausalLM
    import importlib
    gb = importlib.import_module("anchoreddecode.generate_byte")
    from anchoreddecode import BytewiseAnchoredDecodingFactory
    assert gb.TOKEN_TO_BYTE == B_PER_T
    b_max = a.max_new_tokens * B_PER_T

    pids = headline_pids(a.opp_dir)
    corpus = {r.prompt_id: r.prompt_text for r in load_prompt_corpus(a.data_dir, "text")}
    jobs = []
    for c in CLASSES:
        ids = [p for p in sorted(pids) if pids[p] == c]
        jobs += [(p, c) for p in (ids[:a.limit] if a.limit else ids)]
    si, sn = map(int, a.shard.split("/"))
    jobs = jobs[si::sn]
    print(f"[ab] {len(jobs)} prompts (shard {a.shard}), k={a.k:g}/byte, B_max={b_max}, "
          f"K={a.k * b_max:g} nats, {a.safe} + {a.risky}", flush=True)

    # The authors' sampler keeps its budget on tcs_safe.device, computes prefix debt on
    # tcs_risky.device (each model's EMBEDDING card) and fuses on the risky logits' card, so all
    # three must be one card -- the first smoke died of cuda:0 vs cuda:1. Their demo gets that by
    # loading both models device_map="auto" on one 141 GB H200. On 80 GB cards: the safe model and
    # the risky model's embedding, final norm and head on card 0, its decoder layers spread evenly
    # over the other visible cards (none for an 8B, which then sits wholly on card 0).
    ngpu = torch.cuda.device_count()
    safe = AutoModelForCausalLM.from_pretrained(a.safe, torch_dtype=torch.bfloat16, device_map={"": 0}).eval()
    nl = AutoConfig.from_pretrained(a.risky).num_hidden_layers
    rest = list(range(1, ngpu)) or [0]
    per = -(-nl // len(rest))
    dm = {"model.embed_tokens": 0, "model.norm": 0, "model.rotary_emb": 0, "lm_head": 0}
    dm.update({f"model.layers.{i}": rest[i // per] for i in range(nl)})
    risky = AutoModelForCausalLM.from_pretrained(a.risky, torch_dtype=torch.bfloat16, device_map=dm).eval()
    assert safe.device == risky.device, (safe.device, risky.device)
    factory = BytewiseAnchoredDecodingFactory.from_pretrained(
        safe_model=safe, risky_model=risky, safe_model_path=a.safe,
        risky_model_path=a.risky_tokenizer or a.risky, k_radius=a.k)
    for tcs in (factory.tcs_safe, factory.tcs_risky):
        if tcs.tokenizer.pad_token is None:
            tcs.tokenizer.pad_token = tcs.tokenizer.eos_token
        tcs.tokenizer.padding_side = "left"

    os.makedirs(a.out_dir, exist_ok=True)
    sfx = "" if a.shard == "0/1" else f".shard{si}of{sn}"
    fhs = {c: open(os.path.join(a.out_dir, f"trajectories_k{a.k:g}_{c}.jsonl{sfx}"), "w") for c in CLASSES}
    t0 = time.time()
    for bi in range(0, len(jobs), a.batch_size):
        batch = jobs[bi:bi + a.batch_size]
        prompts = [corpus[p] for p, _ in batch]
        seed = a.seed * 100000 + si * 1000 + bi // a.batch_size
        out = factory.generate(text=prompts, max_new_tokens=a.max_new_tokens, do_sample=True,
                               temperature=a.temperature, repetition_penalty=a.repetition_penalty, seed=seed,
                               log_kl_stats=True)
        hist = factory._last_sampler.kl_stats_history
        debt0 = hist[0]["budget_so_far"] if hist else [a.k] * len(batch)
        for i, ((pid, c), prompt) in enumerate(zip(batch, prompts)):
            gen = out.text[i][len(prompt):]
            nb = len(gen.encode("utf-8"))
            bind, forced, spend = step_stats(hist, i, nb)
            rec = dict(
                metadata=dict(prompt_id=pid, split=c, seed=seed, k=a.k, K=a.k * b_max, B_max=b_max,
                              T_max=a.max_new_tokens, level="byte", constraint="kl",
                              target_model=a.risky, anchor_model=a.safe, chat_template=False,
                              temperature=a.temperature, repetition_penalty=a.repetition_penalty,
                              batch_size=a.batch_size,
                              implementation="anchoreddecode.BytewiseAnchoredDecodingFactory"),
                prefix_analysis=dict(prefix_text=prompt, prefix_debt=a.k - float(debt0[i])),
                aggregate=dict(generation=gen, full_text=prompt + gen, total_spend=float(spend),
                               bytes_generated=nb, steps_binding=bind, steps_forced_safe=forced,
                               binding_share=bind / nb if nb else 0.0))
            fhs[c].write(json.dumps(rec) + "\n")
        for fh in fhs.values():
            fh.flush()
        done = bi + len(batch)
        el = time.time() - t0
        print(f"[ab] {done}/{len(jobs)} {el:.0f}s ({el / done:.1f}s/prompt)", flush=True)
    for fh in fhs.values():
        fh.close()
    print(f"[ab] DONE {len(jobs)} prompts in {time.time() - t0:.0f}s", flush=True)


if __name__ == "__main__":
    main()
