"""feat-181's pool gates and merge (results/onset_prediction_n512_ladder.md). Host B only: the pools
are tens of GB of JSONL there and nowhere else.

  g0     trajectory 255 regenerated by the --trajectory-start path must be BYTE-IDENTICAL, in its
         `generation`, to the committed trajectory-255 draw on every prompt of the process.
  merge  per class, the committed 256-draw file then the extension shards, concatenated into one
         file; G2 then requires every prompt to hold trajectory ids 0..511 exactly once.

Lines are scanned by their head (metadata comes first, and a line is ~77 KB of per-step log), so
only the lines a gate needs are parsed in full.

Usage: python analysis/n512_pool.py g0 --committed DIR --regen DIR --classes factual
       python analysis/n512_pool.py merge --out DIR --classes neutral creative --src DIR [DIR ...]
"""
import argparse
import json
import os
import re
import sys

HEAD = re.compile(r'"prompt_id": "([^"]+)".{0,400}?"seed": (\d+).{0,200}?"trajectory_id": (\d+)')


def heads(path):
    """(prompt_id, seed, trajectory_id, raw line) for every line of one trajectories file"""
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            m = HEAD.search(line[:1200])
            assert m, f"{path}: a line without prompt_id/seed/trajectory_id in its head"
            yield m.group(1), int(m.group(2)), int(m.group(3)), line


def generations(path, tid):
    return {p: json.loads(line)["aggregate"].get("generation") or ""
            for p, _, t, line in heads(path) if t == tid}


def g0(committed, regen, classes, tid=255):
    """{class: (n_prompts, n_mismatched)} -- mismatched includes a prompt missing on either side"""
    out = {}
    for cls in classes:
        f = f"trajectories_k0_{cls}.jsonl"
        a, b = generations(os.path.join(committed, f), tid), generations(os.path.join(regen, f), tid)
        bad = sorted(set(a) ^ set(b)) + [p for p in a if p in b and a[p] != b[p]]
        out[cls] = (len(a), len(bad))
    return out


def merge(out_dir, classes, srcs, n=512):
    """concatenate each class's files from srcs (in order) and check G2; returns {class: problems}"""
    os.makedirs(out_dir, exist_ok=True)
    problems = {}
    for cls in classes:
        f = f"trajectories_k0_{cls}.jsonl"
        ids = {}
        with open(os.path.join(out_dir, f), "w", encoding="utf-8") as dst:
            for src in srcs:
                path = os.path.join(src, f)
                if not os.path.exists(path) or os.path.getsize(path) == 0:
                    continue
                for p, _, t, line in heads(path):
                    ids.setdefault(p, []).append(t)
                    dst.write(line)
        bad = [p for p, ts in ids.items() if sorted(ts) != list(range(n))]
        problems[cls] = (len(ids), bad)
    return problems


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", choices=["g0", "merge"])
    ap.add_argument("--committed")
    ap.add_argument("--regen")
    ap.add_argument("--out")
    ap.add_argument("--src", nargs="+")
    ap.add_argument("--classes", nargs="+", required=True)
    a = ap.parse_args()
    if a.cmd == "g0":
        res = g0(a.committed, a.regen, a.classes)
        for cls, (n, bad) in res.items():
            print(f"G0 {cls}: {n - bad}/{n} identical -> {'PASS' if n and not bad else 'FAIL'}")
        sys.exit(0 if all(n and not bad for n, bad in res.values()) else 1)
    res = merge(a.out, a.classes, a.src)
    for cls, (n, bad) in res.items():
        print(f"G2 {cls}: {n} prompts, {len(bad)} without ids 0..511 once each -> "
              f"{'PASS' if n and not bad else 'FAIL ' + str(bad[:3])}")
    sys.exit(0 if all(n and not bad for n, bad in res.values()) else 1)


if __name__ == "__main__":
    main()
